export { default as Layout } from './Layout';
export { default as Nav } from './Nav';
export { default as Hero } from './Hero';
export { default as Intro } from './Intro';
export { default as Principles } from './Principles';
export { default as Areas } from './Areas';
export { default as Team } from './Team';
export { default as Footer } from './Footer';
export { default as IconTaxLaw } from './IconTaxLaw';
export { default as IconCivilLitigation } from './IconCivilLitigation';
export { default as IconAppeals } from './IconAppeals';
export { default as IconBusinessLaw } from './IconBusinessLaw';
// export { default as IconIp } from './IconIp';
// export { default as IconEntLaw } from './IconEntLaw';
export { default as IconTaxMitigation } from './IconTaxMitigation';
export { default as IconAssetProtection } from './IconAssetProtection';
export { default as Wheel } from './Wheel';
